# Generated by Django 5.2.3 on 2025-07-29 08:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('home', 'Home'), ('health', 'Health'), ('finance', 'Finance'), ('study', 'Study / Education'), ('meetings', 'Meetings'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('other', 'others')], max_length=50, verbose_name='Category of the task')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'task_manager_category',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='deadline')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('pending', 'Pending')], default='new', max_length=20, verbose_name='Status of the task')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 8, 5, 8, 4, 41, 457664, tzinfo=datetime.timezone.utc), verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('categories', models.ManyToManyField(related_name='tasks', to='task_manager.category', verbose_name='Category of the task')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'task_manager_task',
                'ordering': ['-created_at'],
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('pending', 'Pending')], default='new', verbose_name='Status of the subtask')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 8, 5, 8, 4, 41, 459812, tzinfo=datetime.timezone.utc), verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task_manager.task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'db_table': 'task_manager_subtask',
                'ordering': ['-created_at'],
                'unique_together': {('title',)},
            },
        ),
    ]
