# Generated by Django 5.2.3 on 2025-06-23 12:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Category of the task')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='deadline')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('pending', 'Pending')], default='new', verbose_name='Status of the task')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 11, 39, 823228, tzinfo=datetime.timezone.utc), verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('categories', models.ManyToManyField(related_name='tasks', to='task_manager.category', verbose_name='Category of the task')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('pending', 'Pending')], default='new', verbose_name='Status of the subtask')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 11, 39, 825753, tzinfo=datetime.timezone.utc), verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
        ),
    ]
