# Generated by Django 5.2.3 on 2025-06-23 12:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('home', 'Home'), ('health', 'Health'), ('finance', 'Finance'), ('study', 'Study / Education'), ('meetings', 'Meetings'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('other', 'others')], verbose_name='Category of the task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 30, 31, 481950, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='task_manager.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 30, 31, 479127, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
    ]
