# Generated by Django 5.2.3 on 2025-07-29 10:16

import task_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=task_manager.models.default_deadline, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=task_manager.models.default_deadline, verbose_name='Deadline'),
        ),
    ]
