# Generated by Django 5.2.3 on 2025-06-23 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_category_name_alter_subtask_deadline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='tasks', to='task_manager.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 46, 19, 690097, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 12, 46, 19, 687441, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
    ]
