# Generated by Django 5.2.3 on 2025-06-29 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 6, 19, 12, 46, 920279, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 6, 19, 12, 46, 918041, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
    ]
