# Generated by Django 5.2.3 on 2025-07-14 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_subtask_deadline_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 19, 33, 35, 431978, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 19, 33, 35, 429856, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
    ]
