# Generated by Django 5.2.3 on 2025-07-21 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_subtask_deadline_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 20, 46, 59, 770027, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 20, 46, 59, 767474, tzinfo=datetime.timezone.utc), verbose_name='Deadline'),
        ),
    ]
