# Generated by Django 5.2.3 on 2025-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c#', 'C#'), ('c++', 'C++'), ('java', 'Java')])),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('jun', 'Junior'), ('mid', 'Middle'), ('sen', 'Senior'), ('tl', 'Team-Lead')])),
                ('projects', models.ManyToManyField(related_name='devs', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('Q&A', 'Q&A'), ('design', 'Design'), ('devops', 'DevOPS'), ('test', 'Test')], max_length=100)),
                ('projects', models.ManyToManyField(related_name='tags', to='project.project')),
            ],
        ),
    ]
