# Generated by Django 5.2.3 on 2025-06-23 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('jun', 'Junior'), ('mid', 'Middle'), ('sen', 'Senior'), ('tl', 'Team-Lead')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('c#', 'C#'), ('c++', 'C++'), ('java', 'Java')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='project.dev')),
            ],
        ),
        migrations.AddField(
            model_name='dev',
            name='projects',
            field=models.ManyToManyField(related_name='devs', to='project.project'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('Q&A', 'Q&A'), ('design', 'Design'), ('devops', 'DevOPS'), ('test', 'Test')], max_length=100, unique=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='tags', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('pending', 'Pending')], default='new')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='project.tag')),
            ],
        ),
    ]
