# Generated by Django 5.2.3 on 2025-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('country', models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('DE', 'Germany')], default='FR', help_text='Where are you from?')),
            ],
        ),
    ]
