# Generated by Django 5.2.3 on 2025-06-21 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
